title: 筒井・遠藤研究室
logo: ./assets/img/logo.png
email: <a href="https://forms.gle/XVSrAZTMDB6gsxRJ7">Form</a>
description: CLAM Lab.<br>東京科学大学<br>Institute of Science Tokyo
show_downloads: false
google_analytics: 
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - 
  - name: Japanese
    icon: <img src="./assets/img/jp.png" alt="en" style="width:1em; height:0.8em; vertical-align:0em;">
    link: ./index.html
  - name: English
    icon: <img src="./assets/img/en.png" alt="en" style="width:1em; height:0.8em; vertical-align:0em;">
    link: ./index_en.html
  - name: IGP - International Graduation Program
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: ./IGP.html
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/clam-lab
  - name: Science Tokyo
    icon: <img src="./assets/img/symbol.jpg" alt="en" style="width:1em; height:1em; vertical-align:-0.18em;">
    link: https://www.isct.ac.jp/ja
  - name: YASKAWA ELECTRIC CORPORATION
    icon: <img src="./assets/img/yaskawa.png" alt="en" style="width:1em; height:1em; vertical-align:-0.18em;">
    link: https://www.yaskawa.co.jp

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]


url: "https://DrRayCobb.github.io"
baseurl: "/"